modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="toadlib"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''Library for my mods. Contains utilities & abstractions.'''

[[dependencies.toadlib]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.toadlib]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

